###################
# Power saving
###################
- alias: "Shutdown zeller if not used"
  id: '6aec65cab2924c63592b04b3af477d40'
  trigger:
    platform: numeric_state
    entity_id: sensor.zeller_watts
    below: 5
    for:
      minutes: 5
  action:
    service: homeassistant.turn_off
    entity_id: switch.zeller

- alias: "Shutdown kelbimbo if not used"
  id: 'bb910f8fbd16d8f1a1cc11ccd6ee8a8a'
  trigger:
    platform: numeric_state
    entity_id: sensor.kelbimbo_current
    below: 5
    for:
      minutes: 5
  action:
    service: homeassistant.turn_off
    entity_id: switch.kelbimbo

###################
# Opple
###################
- alias: "Opple - zeller toggle"
  id: '7f25b6a804855544c7d3b0a612a15a19'
  trigger:
    platform: mqtt
    topic: zigbee2mqtt/aqara_opple
  condition:
    condition: template
    value_template: '{{ trigger.payload_json.action == "button_1_single"}}'
  action:
  - service: switch.toggle
    entity_id: switch.zeller

- alias: "Opple - kelbimbo toggle"
  id: 'a59ad841ddb6359aead69093e0629435'
  trigger:
    platform: mqtt
    topic: zigbee2mqtt/aqara_opple
  condition:
    condition: template
    value_template: '{{ trigger.payload_json.action == "button_2_single"}}'
  action:
  - service: switch.toggle
    entity_id: switch.kelbimbo

- alias: "Opple - articsoka toggle"
  trigger:
    platform: mqtt
    topic: zigbee2mqtt/aqara_opple
  condition:
    condition: template
    value_template: '{{ trigger.payload_json.action == "button_3_single"}}'
  action:
  - service: switch.toggle
    entity_id: switch.articsoka

- alias: "Opple - tradfri bulb toggle"
  id: '6a3cb61951fe27c5c47cc17c76589578'
  trigger:
    platform: mqtt
    topic: zigbee2mqtt/aqara_opple
  condition:
    condition: template
    value_template: '{{ trigger.payload_json.action == "button_4_single"}}'
  action:
  - service: light.toggle
    entity_id: light.tradfri_light

- alias: "Opple - purifier toggle"
  id: 'b21e11bec8530a810c555bd7b80925f6'
  trigger:
    platform: mqtt
    topic: zigbee2mqtt/aqara_opple
  condition:
    condition: template
    value_template: '{{ trigger.payload_json.action == "button_5_single"}}'
  action:
  - service: fan.toggle
    entity_id: fan.xiaomi_miio_device

- alias: "Opple - humidifier toggle"
  trigger:
    platform: mqtt
    topic: zigbee2mqtt/aqara_opple
  condition:
    condition: template
    value_template: '{{ trigger.payload_json.action == "button_6_single"}}'
  action:
  - service: fan.toggle
    entity_id: fan.xiaomi_miio_device_2

###################
# Air Purifier
###################
- alias: "Air Purifier mode change"
  id: 'bc8ef35ad9177454f6c27c77fd7bd52a'
  trigger:
    entity_id: input_select.xiaomi_airpurifier_mode
    platform: state
  action:
    service: fan.set_speed
    data_template:
      entity_id: fan.xiaomi_miio_device
      speed: '{{ states.input_select.xiaomi_airpurifier_mode.state }}'

- alias: "Air Purifier mode changed"
  id: '2f23ac3b961d6759163ae41a2a9c242b'
  trigger:
    platform: state
    entity_id: fan.xiaomi_miio_device
  action:
    service: input_select.select_option
    entity_id: input_select.xiaomi_airpurifier_mode
    data_template:
      option: '{{ states.fan.xiaomi_miio_device.attributes.speed }}'

- alias: "Air Purifier favorite level change"
  id: '1c648470f2c3ddea88fd7bece73afd1a'
  trigger:
    entity_id: input_number.xiaomi_airpurifier_favorite_level
    platform: state
  action:
    service: xiaomi_miio.fan_set_favorite_level
    data_template:
      entity_id: fan.xiaomi_miio_device
      level: '{{ states.input_number.xiaomi_airpurifier_favorite_level.state | int }}'

- alias: "Air Purifier favorite level changed"
  id: '67f48fa64f07a69bc557e96a45c0e7bf'
  trigger:
    platform: state
    entity_id: fan.xiaomi_miio_device
  action:
    service: input_number.set_value
    entity_id: input_number.xiaomi_airpurifier_favorite_level
    data_template:
      value: '{{ states.fan.xiaomi_miio_device.attributes.favorite_level }}'

###################
# Air Humidifier
###################
- alias: "Air Humidifier mode change"
  trigger:
    entity_id: input_select.xiaomi_humidifier_mode
    platform: state
  action:
    service: fan.set_speed
    data_template:
      entity_id: fan.xiaomi_miio_device_2
      speed: '{{ states.input_select.xiaomi_humidifier_mode.state }}'

- alias: "Air Humidifier mode changed"
  trigger:
    platform: state
    entity_id: fan.xiaomi_miio_device_2
  action:
    service: input_select.select_option
    entity_id: input_select.xiaomi_humidifier_mode
    data_template:
      option: '{{ states.fan.xiaomi_miio_device_2.attributes.speed }}'

- alias: "Air Humidifier target humidity change"
  trigger:
    entity_id: input_number.xiaomi_humidifier_target_humidity
    platform: state
  action:
    service: xiaomi_miio.fan_set_target_humidity
    data_template:
      entity_id: fan.xiaomi_miio_device_2
      humidity: '{{ states.input_number.xiaomi_humidifier_target_humidity.state | int }}'

- alias: "Air Humidifier target humidity changed"
  trigger:
    platform: state
    entity_id: fan.xiaomi_miio_device_2
  action:
    service: input_number.set_value
    entity_id: input_number.xiaomi_humidifier_target_humidity
    data_template:
      value: '{{ states.fan.xiaomi_miio_device_2.attributes.target_humidity }}'

- alias: "Air Humidifier LED brightness change"
  trigger:
    entity_id: input_number.xiaomi_humidifier_brightness
    platform: state
  action:
    service: xiaomi_miio.fan_set_led_brightness
    data_template:
      entity_id: fan.xiaomi_miio_device_2
      brightness: '{{ states.input_number.xiaomi_humidifier_brightness.state | int }}'

- alias: "Air Humidifier LED brightness changed"
  trigger:
    platform: state
    entity_id: fan.xiaomi_miio_device_2
  action:
    service: input_number.set_value
    entity_id: input_number.xiaomi_humidifier_brightness
    data_template:
      value: '{{ states.fan.xiaomi_miio_device_2.attributes.led_brightness }}'

###################
# Torrents
###################
- alias: "Torrents started"
  id: '686b317da22d0db492c60b570414b698'
  trigger:
    platform: event
    event_type: transmission_started_torrent
  action:
    service: notify.slack_bot_transmission
    data_template:
      title: Torrent completed!
      message: ''
      data:
        blocks_template:
          - type: section
            text:
              type: plain_text
              text: 'Started downloading of {{trigger.event.data.name}}'

- alias: "Torrents done"
  id: '441ec1de12f22d88fb2332ffefa6d439'
  trigger:
    platform: event
    event_type: transmission_downloaded_torrent
  action:
    service: notify.slack_bot_transmission
    data_template:
      title: Torrent completed!
      message: ''
      data:
        blocks_template:
          - type: section
            text:
              type: plain_text
              text: 'Downloading of {{trigger.event.data.name}} is finished'
